name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      enviroments: ${{ steps.enviroments.outputs.value }}
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v3.0.0
      - id: enviroments
        run: |
          env_list='"dev"'
          for e in "int" "testing"
          do
            if [[ ${{ contains(github.event.head_commit.message, "/deploy $e") }} ]]; then
              env_list+=",\"$e\""
            fi
          done
          echo "value=[$env_list]" >> $GITHUB_OUTPU
      - run: |
          echo "${{ steps.enviroments.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.enviroments)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
