name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v3.0.0
      - id: m1
        run: |
          eList='dev';
          eList+="prod"
          if ${{ contains(github.event.head_commit.message, '/deploy int') }} 
            eList+="int"
          fi
          echo "value=[$(eList[@])]" >> $GITHUB_OUTPU
      - id: matrix
        run: |
          echo "value=[\"a\", \"b\", \"c\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
